export const movies = {
  "page": 1,
  "results": [{
      "adult": false,
      "backdrop_path": "/v2LilmCylr3bL9TCZSj6syjowZh.jpg",
      "id": 937278,
      "title": "A Man Called Otto",
      "original_language": "en",
      "original_title": "A Man Called Otto",
      "overview": "When a lively young family moves in next door, grumpy widower Otto Anderson meets his match in a quick-witted, pregnant woman named Marisol, leading to an unlikely friendship that turns his world upside down.",
      "poster_path": "/130H1gap9lFfiTF9iDrqNIkFvC9.jpg",
      "media_type": "movie",
      "genre_ids": [35, 18],
      "popularity": 287.34,
      "release_date": "2022-12-28",
      "video": false,
      "vote_average": 7.644,
      "vote_count": 313
  }, {
      "adult": false,
      "backdrop_path": "/wVxlmhk4OS2eCr0wTQcM4zJ20ml.jpg",
      "id": 906221,
      "title": "Magic Mike's Last Dance",
      "original_language": "en",
      "original_title": "Magic Mike's Last Dance",
      "overview": "Mike Lane takes to the stage again after a lengthy hiatus, following a business deal that went bust, leaving him broke and taking bartender gigs in Florida. For what he hopes will be one last hurrah, Mike heads to London with a wealthy socialite who lures him with an offer he can’t refuse… and an agenda all her own. With everything on the line, once Mike discovers what she truly has in mind, will he—and the roster of hot new dancers he’ll have to whip into shape—be able to pull it off?",
      "poster_path": "/bTKyjTlD8qJOiRkHZoSOx5D1KWg.jpg",
      "media_type": "movie",
      "genre_ids": [35, 18, 10749],
      "popularity": 138.813,
      "release_date": "2023-02-09",
      "video": false,
      "vote_average": 6.7,
      "vote_count": 51
  }, {
      "adult": false,
      "backdrop_path": "/6VX3TrYBtnMOHp3v44lIWWnEp7N.jpg",
      "id": 852096,
      "title": "We Have a Ghost",
      "original_language": "en",
      "original_title": "We Have a Ghost",
      "overview": "After Kevin finds a ghost named Ernest haunting his new home, he becomes an overnight social media sensation. But when Kevin and Ernest go rogue to investigate the mystery of the latter's past, they become targets of the CIA.",
      "poster_path": "/xo0fgAUoEeVQ7KsKeMWypyglvnf.jpg",
      "media_type": "movie",
      "genre_ids": [14, 10751, 35, 12],
      "popularity": 339.473,
      "release_date": "2023-02-24",
      "video": false,
      "vote_average": 6.698,
      "vote_count": 139
  }, {
      "adult": false,
      "backdrop_path": "/sANUefL2v8VI6fSfK3gWAG3XBt4.jpg",
      "id": 631842,
      "title": "Knock at the Cabin",
      "original_language": "en",
      "original_title": "Knock at the Cabin",
      "overview": "While vacationing at a remote cabin, a young girl and her two fathers are taken hostage by four armed strangers who demand that the family make an unthinkable choice to avert the apocalypse. With limited access to the outside world, the family must decide what they believe before all is lost.",
      "poster_path": "/dm06L9pxDOL9jNSK4Cb6y139rrG.jpg",
      "media_type": "movie",
      "genre_ids": [27, 9648, 53],
      "popularity": 4083.809,
      "release_date": "2023-02-01",
      "video": false,
      "vote_average": 6.524,
      "vote_count": 645
  }, {
      "adult": false,
      "backdrop_path": "/r7Dfg9aRZ78gJsmDlCirIIlNH3d.jpg",
      "id": 785084,
      "title": "The Whale",
      "original_language": "en",
      "original_title": "The Whale",
      "overview": "A reclusive English teacher suffering from severe obesity attempts to reconnect with his estranged teenage daughter for one last chance at redemption.",
      "poster_path": "/jQ0gylJMxWSL490sy0RrPj1Lj7e.jpg",
      "media_type": "movie",
      "genre_ids": [18],
      "popularity": 844.847,
      "release_date": "2022-12-09",
      "video": false,
      "vote_average": 7.978,
      "vote_count": 628
  }, {
      "adult": false,
      "backdrop_path": "/pxJbfnMIQQxCrdeLD0zQnWr6ouL.jpg",
      "id": 1077280,
      "title": "Die Hart",
      "original_language": "en",
      "original_title": "Die Hart",
      "overview": "Follows a fictionalized version of Kevin Hart, as he tries to become an action movie star. He attends a school run by Ron Wilcox, where he attempts to learn the ropes on how to become one of the industry's most coveted action stars.",
      "poster_path": "/1EnBjTJ5utgT1OXYBZ8YwByRCzP.jpg",
      "media_type": "movie",
      "genre_ids": [28, 35, 53],
      "popularity": 257.888,
      "release_date": "2023-02-22",
      "video": false,
      "vote_average": 6.729,
      "vote_count": 70
  }, {
      "adult": false,
      "backdrop_path": "/26YLjaC1udGEmSvlM1P5eBGWO5h.jpg",
      "id": 677179,
      "title": "Creed III",
      "original_language": "en",
      "original_title": "Creed III",
      "overview": "After dominating the boxing world, Adonis Creed has been thriving in both his career and family life. When a childhood friend and former boxing prodigy, Damien Anderson, resurfaces after serving a long sentence in prison, he is eager to prove that he deserves his shot in the ring. The face-off between former friends is more than just a fight. To settle the score, Adonis must put his future on the line to battle Damien - a fighter who has nothing to lose.",
      "poster_path": "/cvsXj3I9Q2iyyIo95AecSd1tad7.jpg",
      "media_type": "movie",
      "genre_ids": [18, 28],
      "popularity": 435.33,
      "release_date": "2023-03-01",
      "video": false,
      "vote_average": 7.024,
      "vote_count": 21
  }, {
      "adult": false,
      "backdrop_path": "/b1Y8SUb12gPHCSSSNlbX4nB3IKy.jpg",
      "id": 315162,
      "title": "Puss in Boots: The Last Wish",
      "original_language": "en",
      "original_title": "Puss in Boots: The Last Wish",
      "overview": "Puss in Boots discovers that his passion for adventure has taken its toll: He has burned through eight of his nine lives, leaving him with only one life left. Puss sets out on an epic journey to find the mythical Last Wish and restore his nine lives.",
      "poster_path": "/kuf6dutpsT0vSVehic3EZIqkOBt.jpg",
      "media_type": "movie",
      "genre_ids": [16, 12, 35],
      "popularity": 2378.726,
      "release_date": "2022-12-07",
      "video": false,
      "vote_average": 8.452,
      "vote_count": 4134
  }, {
      "adult": false,
      "backdrop_path": "/gslT8t964rYXyqRcqrxFh77ikyb.jpg",
      "id": 640146,
      "title": "Ant-Man and the Wasp: Quantumania",
      "original_language": "en",
      "original_title": "Ant-Man and the Wasp: Quantumania",
      "overview": "Super-Hero partners Scott Lang and Hope van Dyne, along with with Hope's parents Janet van Dyne and Hank Pym, and Scott's daughter Cassie Lang, find themselves exploring the Quantum Realm, interacting with strange new creatures and embarking on an adventure that will push them beyond the limits of what they thought possible.",
      "poster_path": "/ngl2FKBlU4fhbdsrtdom9LVLBXw.jpg",
      "media_type": "movie",
      "genre_ids": [12, 878, 35],
      "popularity": 1025.636,
      "release_date": "2023-02-10",
      "video": false,
      "vote_average": 6.504,
      "vote_count": 811
  }, {
      "adult": false,
      "backdrop_path": "/tpu9ILyknA4oE3vYUfPK7C4Aztw.jpg",
      "id": 1081313,
      "title": "Tonight You're Sleeping with Me",
      "original_language": "pl",
      "original_title": "Dzisiaj śpisz ze mną",
      "overview": "Stuck in a passionless marriage, a journalist must choose between her distant but loving husband and a younger ex-boyfriend who has reentered her life",
      "poster_path": "/sexnKxpAOl0wfixYC3RataZD4pI.jpg",
      "media_type": "movie",
      "genre_ids": [10749, 18],
      "popularity": 43.835,
      "release_date": "2023-03-01",
      "video": false,
      "vote_average": 8.0,
      "vote_count": 2
  }, {
      "adult": false,
      "backdrop_path": "/j9j7a5rnIKaFiWbuMzC41xgFE4r.jpg",
      "id": 536554,
      "title": "M3GAN",
      "original_language": "en",
      "original_title": "M3GAN",
      "overview": "A brilliant toy company roboticist uses artificial intelligence to develop M3GAN, a life-like doll programmed to emotionally bond with her newly orphaned niece. But when the doll's programming works too well, she becomes overprotective of her new friend with terrifying results.",
      "poster_path": "/d9nBoowhjiiYc4FBNtQkPY7c11H.jpg",
      "media_type": "movie",
      "genre_ids": [878, 27, 35],
      "popularity": 1133.805,
      "release_date": "2022-12-28",
      "video": false,
      "vote_average": 7.508,
      "vote_count": 1834
  }, {
      "adult": false,
      "backdrop_path": "/xDMIl84Qo5Tsu62c9DGWhmPI67A.jpg",
      "id": 505642,
      "title": "Black Panther: Wakanda Forever",
      "original_language": "en",
      "original_title": "Black Panther: Wakanda Forever",
      "overview": "Queen Ramonda, Shuri, M’Baku, Okoye and the Dora Milaje fight to protect their nation from intervening world powers in the wake of King T’Challa’s death.  As the Wakandans strive to embrace their next chapter, the heroes must band together with the help of War Dog Nakia and Everett Ross and forge a new path for the kingdom of Wakanda.",
      "poster_path": "/sv1xJUazXeYqALzczSZ3O6nkH75.jpg",
      "media_type": "movie",
      "genre_ids": [28, 12, 878],
      "popularity": 2782.773,
      "release_date": "2022-11-09",
      "video": false,
      "vote_average": 7.402,
      "vote_count": 3684
  }, {
      "adult": false,
      "backdrop_path": "/ovM06PdF3M8wvKb06i4sjW3xoww.jpg",
      "id": 76600,
      "title": "Avatar: The Way of Water",
      "original_language": "en",
      "original_title": "Avatar: The Way of Water",
      "overview": "Set more than a decade after the events of the first film, learn the story of the Sully family (Jake, Neytiri, and their kids), the trouble that follows them, the lengths they go to keep each other safe, the battles they fight to stay alive, and the tragedies they endure.",
      "poster_path": "/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg",
      "media_type": "movie",
      "genre_ids": [878, 12, 28],
      "popularity": 1224.144,
      "release_date": "2022-12-14",
      "video": false,
      "vote_average": 7.738,
      "vote_count": 5548
  }, {
      "adult": false,
      "backdrop_path": "/mIrNZQw4u9fpGyllxoYEmQrdYR5.jpg",
      "id": 782936,
      "title": "Nocebo",
      "original_language": "en",
      "original_title": "Nocebo",
      "overview": "A fashion designer hires a nanny from the Philippines to assist her in caring for her family while she is suffering from what she believes is a tick-related illness. The nanny uses traditional Filipino folk healing techniques to help her, but in the process of doing so, she uncovers a horrifying truth about why she is there and why her employer is actually sick.",
      "poster_path": "/3FPnDTlX0LsaU4VD5mc82BMbchA.jpg",
      "media_type": "movie",
      "genre_ids": [9648, 53, 27],
      "popularity": 43.302,
      "release_date": "2022-11-03",
      "video": false,
      "vote_average": 6.25,
      "vote_count": 34
  }, {
      "adult": false,
      "backdrop_path": "/9Rq14Eyrf7Tu1xk0Pl7VcNbNh1n.jpg",
      "id": 646389,
      "title": "Plane",
      "original_language": "en",
      "original_title": "Plane",
      "overview": "After a heroic job of successfully landing his storm-damaged aircraft in a war zone, a fearless pilot finds himself between the agendas of multiple militias planning to take the plane and its passengers hostage.",
      "poster_path": "/qi9r5xBgcc9KTxlOLjssEbDgO0J.jpg",
      "media_type": "movie",
      "genre_ids": [28, 12, 53],
      "popularity": 2266.231,
      "release_date": "2023-01-12",
      "video": false,
      "vote_average": 6.913,
      "vote_count": 710
  }, {
      "adult": false,
      "backdrop_path": "/nAUpDd7iGfESDomaeAWKeNABw4I.jpg",
      "id": 545611,
      "title": "Everything Everywhere All at Once",
      "original_language": "en",
      "original_title": "Everything Everywhere All at Once",
      "overview": "An aging Chinese immigrant is swept up in an insane adventure, where she alone can save what's important to her by connecting with the lives she could have led in other universes.",
      "poster_path": "/w3LxiVYdWWRvEVdn5RYq6jIqkb1.jpg",
      "media_type": "movie",
      "genre_ids": [28, 12, 878],
      "popularity": 260.742,
      "release_date": "2022-03-24",
      "video": false,
      "vote_average": 7.995,
      "vote_count": 3325
  }, {
      "adult": false,
      "backdrop_path": "/cKqk1m6n2lPHZMHNSVYhrnRCiux.jpg",
      "id": 1063422,
      "title": "The Strays",
      "original_language": "en",
      "original_title": "The Strays",
      "overview": "A Black woman's meticulously crafted life of privilege starts to unravel when two strangers show up in her quaint suburban town.",
      "poster_path": "/3OKBFYRVSKkBVJ7WpKogTVQfUqC.jpg",
      "media_type": "movie",
      "genre_ids": [53, 9648, 18],
      "popularity": 240.366,
      "release_date": "2023-02-17",
      "video": false,
      "vote_average": 5.657,
      "vote_count": 137
  }, {
      "adult": false,
      "backdrop_path": "/hUtrCoGrlo3o8juAI1ZzA7F1LX9.jpg",
      "id": 777245,
      "title": "Women Talking",
      "original_language": "en",
      "original_title": "Women Talking",
      "overview": "A group of women in an isolated religious colony struggle to reconcile their faith with a series of sexual assaults committed by the colony's men.",
      "poster_path": "/fIrFR0eTpdNV1AtuZKa0Q7sRAH2.jpg",
      "media_type": "movie",
      "genre_ids": [18],
      "popularity": 90.667,
      "release_date": "2022-12-23",
      "video": false,
      "vote_average": 7.173,
      "vote_count": 81
  }, {
      "adult": false,
      "backdrop_path": "/e8BCc8Jk11dnSffI6ElICLePvLZ.jpg",
      "id": 603692,
      "title": "John Wick: Chapter 4",
      "original_language": "en",
      "original_title": "John Wick: Chapter 4",
      "overview": "With the price on his head ever increasing, John Wick uncovers a path to defeating The High Table. But before he can earn his freedom, Wick must face off against a new enemy with powerful alliances across the globe and forces that turn old friends into foes.",
      "poster_path": "/jPJfq3s7UybktndveSbhwsReYqH.jpg",
      "media_type": "movie",
      "genre_ids": [28, 53, 80],
      "popularity": 206.11,
      "release_date": "2023-03-22",
      "video": false,
      "vote_average": 0.0,
      "vote_count": 0
  }, {
      "adult": false,
      "backdrop_path": "/e4V77sv2MvSbGyViKTXDsgR3fl4.jpg",
      "id": 804150,
      "title": "Cocaine Bear",
      "original_language": "en",
      "original_title": "Cocaine Bear",
      "overview": "An oddball group of cops, criminals, tourists and teens converge in a Georgia forest where a 500-pound black bear goes on a murderous rampage after unintentionally ingesting cocaine.",
      "poster_path": "/gOnmaxHo0412UVr1QM5Nekv1xPi.jpg",
      "media_type": "movie",
      "genre_ids": [28, 35, 27, 80],
      "popularity": 208.738,
      "release_date": "2023-02-22",
      "video": false,
      "vote_average": 7.17,
      "vote_count": 44
  }],
  "total_pages": 1000,
  "total_results": 20000
}